### ISSUE TITLE
For ... of object is not representative

### ISSUE THREAD

**Issue by MMeent** [kpdecker/six-speed#38]
The syntax `for ... of <object>` is defined with <object> being an iterable. The native ECMAScript 'Object' is not an 'Iterable' and should therefore not be benchmarked as if it were, since implementing Iterable just for testing `for ... of`-statements in ES6 and not for the base in ES5 makes the benchmark biased.

**Comment by Pomax** [comment]
To echo this, `for...of` should be compared to `Object.keys(...).forEach(...)`, not `for ... in` which is a completely different kind of behaviour.

**Comment by kpdecker** [comment]
My goal for the tests here was general intent. That test was for iteration of the keys of an object. I wrote the es5 versions of the code trying to focus on what the user wanted to do rather than strict adherence to all of the nuances of the spec which I'd argue that most users are not concerned with. This means that generally I selected the most optimized pattern that I was familiar with out of all ES3 and ES5 constructs when writing the equivalent. Ex: #36 and the use of closures over bind.

That being said if you'd like to submit a PR adding another test I can add it to the test suite (I request that data.json not be included in the PR as I run all of the tests on the same machine with the same code, browser versions, etc, to try to machine things as consistent as possible)

**Comment by tphummel** [comment]
I agree. I would be more interested in seeing the results of `Object.keys(...).forEach(...)` than `for ... in`

**Comment by C-Lodder** [comment]
I've tried running:

```
var data = {'a': 'b', 'c': 'd'};
function fn() {
  var ret = '';
  Object.keys(data).forEach(function(name) {
    ret += data[name];
  });
  return ret;
}

assertEqual(fn(), 'bd');
test(fn);
```

But Buble and Typescript throw:  `Error: AssertError - Expect  to equal bd`

**Comment by C-Lodder** [comment]
Pending PR: https://github.com/kpdecker/six-speed/pull/69
