### ISSUE TITLE
Rerun report in 2020

### ISSUE THREAD

**Issue by mdstaff** [kpdecker/six-speed#72]
Hello, 

This project is pretty awesome!  I noticed the last report date on the report page http://kpdecker.github.io/six-speed/ was "2/13/2019 using babel 7.2.2, babel-runtime 7.3.1 and TypeScript 3.3.3.".  Is it possible to generate new test result data for 2020?

Thanks,
Matt

**Comment by C-Lodder** [comment]
Hi @mdstaff, I will try and compile a report this weekend

**Comment by mdstaff** [comment]
Thanks @C-Lodder for the quick reply 😄 Minor follow-up question.  Is there a process for considering updates to the data.json versions for Chrome and other Chromium browsers? (e.g. stable and 72.X)?

**Comment by C-Lodder** [comment]
No process that I know of. However whenever I run a test, I always use the latest stable version of a browser. Apart from Safari as I don't own a Mac :)

If you have any suggestions, just let me know.

Just an FYI, the report will take a little longer. I'm having tweak a lot of the code due to dependency updates.

**Comment by C-Lodder** [comment]
@mdstaff I've added tests for the following:

- Chrome 80
- Firefox 72
- Node 13.8.0

using the latest dependency versions

**Comment by banchichen** [comment]
@C-Lodder hi, thanks your awesome project,  Is it possible to generate new test result data for 2022?

**Comment by C-Lodder** [comment]
@banchichen - I've re-run the tests and deployed the results for the following:

- Node.js v18.x
- Chrome v106
- Edge (Chromium) v105
- Firefox 105
